// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6y614VHlsuxYMHJ72q0o9f4SoUMrRt8c',
    appId: '1:955881771793:web:5c1ea23b91860d184232b0',
    messagingSenderId: '955881771793',
    projectId: 'banco-int',
    authDomain: 'banco-int.firebaseapp.com',
    databaseURL: 'https://banco-int-default-rtdb.firebaseio.com',
    storageBucket: 'banco-int.appspot.com',
    measurementId: 'G-NTTDX208VB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7Z_8L_slBlqEhCkpuJHz4ABkUkLt28sA',
    appId: '1:955881771793:android:ca7a222505673f2d4232b0',
    messagingSenderId: '955881771793',
    projectId: 'banco-int',
    databaseURL: 'https://banco-int-default-rtdb.firebaseio.com',
    storageBucket: 'banco-int.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQr7XBGhN1b93Frd-oJU8HGyJyiEE6g2A',
    appId: '1:955881771793:ios:e236b8f30dd507024232b0',
    messagingSenderId: '955881771793',
    projectId: 'banco-int',
    databaseURL: 'https://banco-int-default-rtdb.firebaseio.com',
    storageBucket: 'banco-int.appspot.com',
    iosClientId: '955881771793-3m54u6dgbpusficjmmklmqkemlo6jkne.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAppInt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQr7XBGhN1b93Frd-oJU8HGyJyiEE6g2A',
    appId: '1:955881771793:ios:e236b8f30dd507024232b0',
    messagingSenderId: '955881771793',
    projectId: 'banco-int',
    databaseURL: 'https://banco-int-default-rtdb.firebaseio.com',
    storageBucket: 'banco-int.appspot.com',
    iosClientId: '955881771793-3m54u6dgbpusficjmmklmqkemlo6jkne.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAppInt',
  );
}
